#!/bin/bash

# Choose the right executable
if [[ $(uname -s) == 'Darwin' ]]; then OS=mac; else OS=linux; fi

HUB=$(find ~/bin -name hub | grep $OS)
if [[ $HUB != '' ]]; then
    alias hub="$HUB"

    # Give 'git' superpowers
    eval "$(hub alias -s)"
fi